### ISSUE TITLE
Can't get to work with H4nPro

### ISSUE THREAD

**Issue by yureal** [mattogodoy/h6#2]
Hello, I'm trying with my H4nPro and I get:
```
Initializing recorder in port "/dev/cu.usbserial-0001"
Shaking hands
[ERROR] Handshake timeout
```
I found some similar code for regular H4 recorders that seemed to have a shorter initialization sequence, so I've tried that but still getting the same error.

**Comment by mattogodoy** [comment]
I'm sorry you were not able to make it work :(
I spoke with Zoom's support team and they told me that the remote should be compatible with H4, H5 and H6. Sadly I don't have more models other than the H6 to test myself, but I encourage you to make a Pull Request or post here if you find a way to make yours work.

Thanks for the info!

**Comment by surei01** [comment]
Hi, just stumbled across this in trying to get a remote with an ESP32 board to work with the HN4 Pro. Just like yureal I found a different init-sequence for the HN4 in other posts (send 0x00 until response, response should be 0x80, then send 0xA1, response should be 0x80 again, then the connection should be established). So this would not be compatible with the sequence you have for the H6, as the first reply from that device would apparently be 0x81. 
Did anyone get this to work with the HN4 yet?
Many thanks!
